name: Release Publish

on:
  release:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/[0-9]\.[0-9]\.[0-9]/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string


      - run: echo ${{ steps.version.outputs.result }}
